### ISSUE TITLE
400023: Bad Request

### ISSUE THREAD

**Issue by pablo-vivanco** [tableau/server-client-python#872] opened 2021-08-10 04:27 UTC
I had the code working for months and as of last week (when I used the program again after a while), i get error 400023: Bad Request ghen retrieve the list of workbooks for 

Traceback (most recent call last):
  File "d:\Users\Pablo_Vivanco\OneDrive - Edwards Lifesciences\Apps\Projects\python\Tableau InvMi Tool\ew_migration_tool.py", line 144, in <module>
    **workbooks = list(TSC.Pager(server.workbooks, request_options))**
  File "C:\Program Files\Python39\lib\site-packages\tableauserverclient\server\pager.py", line 40, in __iter__
    current_item_list, last_pagination_item = self._endpoint(self._options)
  File "C:\Program Files\Python39\lib\site-packages\tableauserverclient\server\endpoint\endpoint.py", line 138, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\tableauserverclient\server\endpoint\workbooks_endpoint.py", line 39, in get
    server_response = self.get_request(url, req_options)
  File "C:\Program Files\Python39\lib\site-packages\tableauserverclient\server\endpoint\endpoint.py", line 95, in get_request
    return self._make_request(self.parent_srv.session.get, url,
  File "C:\Program Files\Python39\lib\site-packages\tableauserverclient\server\endpoint\endpoint.py", line 57, in _make_request
    self._check_status(server_response)
  File "C:\Program Files\Python39\lib\site-packages\tableauserverclient\server\endpoint\endpoint.py", line 71, in _check_status
    raise ServerResponseError.from_response(server_response.content, self.parent_srv.namespace)
tableauserverclient.server.endpoint.exceptions.ServerResponseError:

        400023: Bad Request
                There was a problem querying the workbooks of user '5e2449bb-867c-409e-af75-c9286e1b7187'.

User '5e2449bb-867c-409e-af75-c9286e1b7187' is me (pablo_vivanco)

I tried retrieving the list of workbooks from 2 different sites, and I get the same error when it gets the workbooks owned by me.

Can you please let me know how I can overcome this problem?

Thanks,
 
PABLO VIVANCO
DATA SOLUTIONS SENIOR ARCHITECT | MASTER DATA MANAGEMENT & ADVANCED ANALYTICS
Edwards Lifesciences LLC | WWW.EDWARDS.COM
OFFICE 949.250.2324 | CELL  949.246.3857 | SKYPE (949) 508-0335

**Comment by bcantoni** [comment] 2021-08-12 19:27
Hi @pablo-vivanco, could you provide a little more detail here to help track down the problem:
* Tableau Server version (or if you're on Tableau Online)
* TSC library version
* A little bit more of the surrounding code so we can try and reproduce the problem

**Comment by jacalata** [comment] 2021-08-24 06:13
I looked through our server logs for this error against your user id, and it looks like you're hitting a known bug we have specifically when fetching workbooks and using the _all_ parameter. If you can update your code to select specific fields instead, it should work while we get a fix through.

**Comment by DoviLilling** [comment] 2021-09-14 14:01
@jacalata - what's the bug #?
I want to introduce an interim fix for this, and want to have a comment to remove the interim fix when the main bug is fixed.
The interim fix already tested and working.

**Comment by DoviLilling** [comment] 2021-09-14 14:15
Well, I guess this is not exactly "open source", as I can't open a branch for my fix.
Anyway, the fix is to just remove the "fields" parameter from the dict.
More specifically, in the file /TSC/server/endpoint/endpoint.py, add the below code between row 106 and 107:
`                # remove this after  - start
                if url == "{0}/sites/{1}/workbooks".format(self.parent_srv.baseurl, self.parent_srv.site_id):
                    parameters["params"].pop("fields")
                # remove this - end`

**Comment by DoviLilling** [comment] 2021-09-14 14:18
Well, I guess this is not exactly "open source", as I can't open a branch for my fix.
Anyway, the fix is to just remove the "fields" parameter from the dict.
More specifically, in the file /TSC/server/endpoint/endpoint.py, add the below code between row 106 and 107:
```
                # remove this after main bug is fixed - start
                if url == "{0}/sites/{1}/workbooks".format(self.parent_srv.baseurl, self.parent_srv.site_id):
                    parameters["params"].pop("fields")
                # remove this after main bug is fixed - end
```

**Comment by bcantoni** [comment] 2021-09-17 02:04
For reference the internal bug number is 1283354. It's being fixed now and should make it out into Tableau Server maintenance releases shortly.

**Closed** 2021-11-10 02:53 UTC
Labels: bug, fixed
