### ISSUE TITLE
Change of Project Ownership via Rest-API

### ISSUE THREAD

**Issue by orappold** [tableau/server-client-python#269] opened 2018-03-01 09:47 UTC
As far as I know the latest REST-API still does not support the change of project ownership. 
It would be huge help to have that function implemented.

**Comment by Santhoshsekar89** [comment] 2018-11-30 23:39
Do we have an update here? Still Im not able to find an option to change the project ownership using Rest-API.

**Comment by Eddie7mail** [comment] 2020-11-25 09:22
The API gives not even the possibility to get the Project Owner. 
It looks like the HTML version may provide the information, at least:
[Permissions Methods](https://help.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_permissions.htm)

`<tsResponse>
  <permissions>
    <project id="project-id" name="project-name" />
      <owner id="project-owner-id" />
    </project>
    <granteeCapabilities>
      <user id="user-id" />
      <capabilities>
        <capability name="capability" mode="Allow-or-Deny" />
        <capability name="capability" mode="Allow-or-Deny" />
        ... additional capabilities ...
      </capabilities>
    </granteeCapabilities>
    <granteeCapabilities>
      <group id="group-id" />
      <capabilities>
        <capability name="capability" mode="Allow-or-Deny" />
        <capability name="capability" mode="Allow-or-Deny" />
        ... additional capabilities ...
      </capabilities>
    </granteeCapabilities>
    ... additional grantee capability sets ...
  </permissions>
</tsResponse>`

**Comment by bcantoni** [comment] 2020-12-01 21:45
I confirmed this is still on the backlog for the REST API to add the capability, then TSC could be updated to expose it. Internal issue 1198685; no ETA yet for when this might happen.

**Comment by jacalata** [comment] 2021-11-10 00:23
closing as a duplicate of  #157

**Closed by jacalata** 2021-11-10 00:23 UTC
Labels: enhancement, Server-Side Enhancement

**Comment by jambesh** [comment] 2022-12-22 00:31
This is a long pending ask and is much needed - 
Why >
People create project in tableau self service and once they leave organization it leave a lot of orphaned projects behind them and some one manually need to change it . We really wanted to assign all the orphaned Project owner to some one who exist in company programmatically through API.
