### ISSUE TITLE
Trying to sign in to a Server over http which has redirect to https setup fails with 'Method Not Allowed' error

### ISSUE THREAD

**Issue by vermaharsh** [tableau/server-client-python#325] opened 2018-07-31 19:34 UTC
Trying to sign in to a server using following code.

```
import tableauserverclient as TSC

cred = TSC.TableauAuth('hverma', '******')
server = TSC.Server('http://alpo')
server.auth.sign_in(cred)
```

It fails with error

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tsi/hverma/.local/share/virtualenvs/search-prototype-CEQSNDUv/lib/python3.4/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 114, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tsi/hverma/.local/share/virtualenvs/search-prototype-CEQSNDUv/lib/python3.4/site-packages/tableauserverclient/server/endpoint/auth_endpoint.py", line 32, in sign_in
    self._check_status(server_response)
  File "/home/tsi/hverma/.local/share/virtualenvs/search-prototype-CEQSNDUv/lib/python3.4/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 66, in _check_status
    raise ServerResponseError.from_response(server_response.content, self.parent_srv.namespace)
tableauserverclient.server.endpoint.exceptions.ServerResponseError: 

    405000: Method Not Allowed
        The HTTP method 'GET' is not supported for the given resource
```

Because, Server it setup to redirect to https but client do not follow it.

If client cannot be made to follow the redirect, can it at least produce better error message so that user can easily rectify the issue by switching to https in Server url.

**Comment by t8y8** [comment] 2018-08-13 21:40
Hmm, it's very inappropriate for the app to redirect a POST, so the error is 'correct'. 
That's actually the underlying HTTP client code throwing the error. 

We could always just try 'https' first, or catch the warning and clean it up as you suggest.

**Comment by reevery** [comment] 2018-08-15 14:07
I can reproduce this with Tableau Online.
```DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): online.tableau.com:443
DEBUG:urllib3.connectionpool:https://online.tableau.com:443 "POST /api/2.3/auth/signin HTTP/1.1" 301 389
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): dub01.online.tableau.com:443
DEBUG:urllib3.connectionpool:https://dub01.online.tableau.com:443 "GET /vizportal/api/external/2.3/auth/signin HTTP/1.1" 405 None
```
However, when using the actual receiving server, it works:
```DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): dub01.online.tableau.com:443
DEBUG:urllib3.connectionpool:https://dub01.online.tableau.com:443 "POST /api/2.3/auth/signin HTTP/1.1" 200 332
```
I agree partially with @t8y8, this should be fixed in the Tableau Apache server, but if it is really an issue not to just to change the server url, then maybe some hack is required.

**Comment by t8y8** [comment] 2018-08-15 17:54
I've delved into this rabbithole before, basically the RFCs and Web Browsers have adopted a behavior of rewriting POSTs to GETs, and most httpclients mirror that behavior. I'm looking into a few options:

1. `requests` might allow us to overwrite that behavior and just force the redirects through
2. We can issue some pre-flight calls or try/retry 301s (This may be more complicated than we want)
3. Do nothing, document

I'll try and take a look ASAP :)

**Comment by eliteminds** [comment] 2019-02-02 18:55
Any update here?

having this issue, when trying to connect to  online.tableau.com

405000: Method Not Allowed
                The HTTP method 'GET' is not supported for the given resource

does it work for somebody?

**Comment by shinchris** [comment] 2019-02-12 21:44
As t8y8 has stated above, this is the standard behavior defined in RFC 2616 for redirecting a POST. I've looked through the `requests` library, but can't seem to find a way to overwrite this behavior.

The workaround for this issue is to sign in to your online site through a web browser, get the full URL of the server, and use that URL to sign in. For example, when I log in to my online site from `https://online.tableau.com`, my site's URL is `https://10ax.online.tableau.com/#/site/mysite`. So I would use `https://10ax.online.tableau.com` as my server address in the python script.

**Comment by eliteminds** [comment] 2019-02-13 18:59
Yes this above and what helped me was to specify the site in parameter,

**Comment by irwando** [comment] 2019-07-25 21:37
Not a bug. As noted we are following RFC and there is a way to do this. 

Step 1 is we should doc this.  If it is a big issue we could consider an enhancement.

**Comment by bcantoni** [comment] 2020-12-09 23:54
I added this specific issue and solution to the "sign in / out" docs page:
https://tableau.github.io/server-client-python/docs/sign-in-out#405000-method-not-allowed-response

**Closed** 2020-12-09 23:53 UTC
Labels: docs, enhancement
