### ISSUE TITLE
Issue while parsing data source revision items

### ISSUE THREAD

**Issue by adbumi** [tableau/server-client-python#1183] opened 2023-01-25 10:35 UTC
The method **tableauserverclient.models.revision_item.RevisionItem.from_response()** expects the attributes "_isCurrent_", "_isDeleted_" and "_createdAt_".
But tableau server provides these attributes with the names "_current_", "_deleted_" and "_publishedAt_". 
The resulting RevisionItem is therefore missing these attributes.

I'm using tableau server version 3.15. Unfortunately I have no possibility to test with other versions. Probably some older version of tableau server provides the attributes with different names. I guess it is necessary to parse the server response conditionally according to the server version.

**Comment by nosnilmot** [comment] 2023-01-29 10:28
This is a duplicate of #1175 (there's also a PR with fixes at #1176)

**Comment by jacalata** [comment] 2023-02-01 01:37
thanks for the heads up :)

**Closed by jacalata** 2023-02-01 01:37 UTC
