### ISSUE TITLE
XML Parser error while retrieving all workbooks from tableau

### ISSUE THREAD

**Issue by jyothimandava** [tableau/server-client-python#677] opened 2020-08-26 22:36 UTC
XML parser error while retrieving all workbooks. This is only happening with workbooks. Projects and views are working fine. And also it is happening only on one tableau server.  able to get all workbooks with same code on dev tableau server. 

with server.auth.sign_in(tableau_auth):
	request_options = TSC.RequestOptions(pagesize=100)
	all_workbooks = list(TSC.Pager(server.workbooks, request_options))
	len(all_workbooks)

is throwing below error

Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tableauserverclient/server/pager.py", line 52, in __iter__
    current_item_list, last_pagination_item = self._load_next_page(last_pagination_item)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tableauserverclient/server/pager.py", line 67, in _load_next_page
    current_item_list, last_pagination_item = self._endpoint(opts)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tableauserverclient/server/endpoint/endpoint.py", line 127, in wrapper
    return func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tableauserverclient/server/endpoint/workbooks_endpoint.py", line 40, in get
    pagination_item = PaginationItem.from_response(server_response.content, self.parent_srv.namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tableauserverclient/models/pagination_item.py", line 24, in from_response
    parsed_response = ET.fromstring(resp)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 1, column 5649

**Comment by bcantoni** [comment] 2020-09-01 17:47
@jyothimandava to help troubleshoot this further, could you provide some more info:

* The version of TSC library you're using (latest is 0.12.1)
* The Tableau Server version for your production server that has the problem
* Tableau Server version for the 'dev' server (if different)

I assume your collection of workbooks are probably different between prod and dev, and it may be an attribute of one specific workbook in production is causing the XML problem.

**Comment by jyothimandava** [comment] 2020-09-15 19:42
@bcantoni  Sorry for the delay in response, Please find the details below

TSC library version 0.12
Tableau server version of production : 2019.4.9
Tableau server version of dev : 2020.3.0

any pointers for identifying the problematic attribute that could cause the issue would be great. 
Thanks

**Comment by bcantoni** [comment] 2020-09-16 01:12
@jyothimandava thanks for that info. Here's something we could try to troubleshoot the issue by enabling the debug log.

Add the following to your script somewhere before you make any TSC calls:

```py
import logging
logging.basicConfig(format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', filename="tsc.log", level="DEBUG")
```

After running your script, the `tsc.log` file file should show all API calls made and the XML responses (look for sections with string "Server response from..."). The last XML snippet in the file (get workbooks) will hopefully be the one that's causing the parsing error.

Rather than posting the XML snippets here, try loading them in <https://xmllint.com/> to see if we can track down the culprit in the XML format.

**Comment by jyothimandava** [comment] 2020-09-16 04:19
@bcantoni Thanks a lot Brian. I was able to get the workbook name which is causing the failure XML Parser
chrome (windows)
![image](https://user-images.githubusercontent.com/70296460/93291636-3b05f000-f7a9-11ea-869d-96888e1cb4bd.png)

There is a weird character in the workbook name which I can see on Tableau from chrome on Windows.  It appears to be a space in Chrome browser of Macbook and invisible in Safari browser of Macbook. That is causing the issue.

Safari
![image](https://user-images.githubusercontent.com/70296460/93291772-9cc65a00-f7a9-11ea-9a7a-03473b991266.png)

Chrome ( Macbook)
![image](https://user-images.githubusercontent.com/70296460/93291809-b8c9fb80-f7a9-11ea-81bf-2899caad8d9e.png)

I will get the name fixed for now and will try to get more details on the character too since its causing the parser to fail

**Comment by bcantoni** [comment] 2020-09-16 04:43
@jyothimandava ah that's great you found the culprit. Yes the workaround will be to replace that character with a normal space.

If you could post here the title string (by copying either from the browser or the debug log), that would be helpful for us to track this down further.

**Comment by jyothimandava** [comment] 2020-09-16 04:50
@bcantoni  . Please find it below.

Hourly TrafficSnapshot

Debug log xml print output just stopped "Hourly Traffic"

name="Hourly Traffic<?xml version='1.0' encoding='UTF-8'?><tsResponse xmlns="http://tableau.com/api" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://tableau.com/api http://tableau.com/api/ts-api-2.3.xsd"><error code="400000"><summary>Bad Request</summary><detail>Payload is either malformed or incomplete</detail></error></tsResponse>

**Comment by bcantoni** [comment] 2020-09-16 15:55
It's hard to tell from the copy & paste but that looks like it might be the [line tabulation character U+000B](https://www.fileformat.info/info/unicode/char/000b/index.htm) in between Traffic and Snapshot.

I've tried to reproduce that with Tableau Online (which is running 2020.3.0), but whatever I'm able to enter in the UI comes through fine through the API/library calls. I tried with a bunch of different space/tab unicode characters but it was all handled correctly.

We'll need to keep investigating to see how those characters might have appeared there and how to better handle that case.

**Comment by bcantoni** [comment] 2020-09-16 19:48
@jyothimandava after an internal discussion we found that there was a bug fixed in Tableau Server 2020.3 which specifically dealt with proper encoding of different Unicode whitespace characters entered in the UI. This seems to match up with what you observed with 2019.4 server (prod) having the issue but 2020.3 (dev) working.

So I think the workaround for now would be to have that workbook name fixed (using normal spaces) and then at some point in the future when you upgrade to 2020.3+ the issue should be properly fixed.

**Comment by jyothimandava** [comment] 2020-09-16 21:00
@bcantoni That's good to know. Thanks a lot for the support Brain. Since it looks like it is fixed in 2020 version, shall I close the bug?

**Comment by bcantoni** [comment] 2020-09-16 22:03
@jyothimandava yep I'll go ahead and close it. I'm glad we got to the bottom of this one.

**Closed by bcantoni** 2020-09-16 22:03 UTC
