### ISSUE TITLE
Pager with users throws TypeError

### ISSUE THREAD

**Issue by reevery** [tableau/server-client-python#107] opened 2016-11-30 16:07 UTC
I am trying to extract the list of users using the Pager:
`print(*TSC.Pager(tableau.users))`

I get the following error:

`  File "metalab_users.py", line 74, in <module>
    print(*tableau_users)
  File "C:\Program Files\Python35\lib\site-packages\tableauserverclient\server\pager.py", line 30, in __iter__
    yield current_item_list.pop(0)
TypeError: pop() takes no arguments (1 given)`

When calling projects with the same code, I get no such error:
`print(*TSC.Pager(tableau.projects))`

**Comment by t8y8** [comment] 2016-11-30 19:08
This was something I discovered at the TC16 hackathon.

The problem is that the `UserItem.from_response` still uses a `set` instead of a list.

https://github.com/tableau/server-client-python/blob/development/tableauserverclient/models/user_item.py#L120

**Comment by t8y8** [comment] 2016-12-02 17:39
fixed in #109

**Closed by t8y8** 2016-12-02 17:39 UTC
Labels: bug
