### ISSUE TITLE
Retrieving subscriptions failed for frequency = Daily, hour (interval) = 24

### ISSUE THREAD

**Issue by ryanstryker** [tableau/server-client-python#1364] opened 2024-03-15 16:38 UTC
tableau_server.subscriptions fails if any subscriptions have schedule frequency="Daily" & interval hours="24"

**Versions**
 - Tableau Cloud: 2024.1.0
 - Python version:  3.11.4
 - TSC library version: 0.30

**To Reproduce**
tableau_server_obj.subscriptions

**Results**
ValueError: Invalid interval 24.0 not in {0.25, 0.5, 2, 1, 4, 6, 8, 12}

**To fix**
update interval_item.py, line 139: 
```
VALID_INTERVALS = {0.25, 0.5, 1, 2, 4, 6, 8, 12, 24}
```

**Comment by jorwoods** [comment] 2024-03-18 03:52
Duplicate of #1354

**Comment by jacalata** [comment] 2024-05-09 23:06
fixed in https://github.com/tableau/server-client-python/pull/1355

**Closed by jacalata** 2024-05-09 23:06 UTC
