### ISSUE TITLE
Call to RequestFactory.Datasource.publish_req_chunked is broken

### ISSUE THREAD

**Issue by sharono011** [tableau/server-client-python#417] opened 2019-03-27 20:48 UTC
The call is sending 3 parameters but the function only accepts 2.

**Comment by LelandWeathers** [comment] 2019-04-01 18:04
This looks to be duplicate of #326 which is fixed and awaiting release

**Comment by shinchris** [comment] 2019-04-08 19:39
This issue should be fixed with the 0.8 release.

**Closed by shinchris** 2019-04-08 19:39 UTC
