### ISSUE TITLE
Hide Views when Publishing a Workbook

### ISSUE THREAD

**Issue by twozeroseven** [tableau/server-client-python#354] opened 2018-11-05 14:45 UTC
A workbook with worksheets set to hidden - which is not uncommon for Workbooks with 1 dashboard view and many hidden worksheets.   Upon publishing via workbook.publish() method the sheets show up on Tableau server as visible.

**Comment by sks786** [comment] 2018-11-15 12:11
Hi Team, 

I also have same concern.
When publishing workbook to the server, hidden sheets are being visible, which we don't want?

Any help on this concern.

Regards,
Subodh kumar

**Comment by sks786** [comment] 2018-11-15 12:12
Hi twozeroseven,

Did you get any solution?
If yes, please help me out.

Regards,
Subodh Kumar

**Comment by twozeroseven** [comment] 2018-11-16 19:43
Is there a better way to setup a workbook to not have hidden sheets?

**Comment by irwando** [comment] 2019-07-25 20:17
This was added to REST API, need to plumb it through:

https://onlinehelp.tableau.com/current/api/rest_api/en-us/REST/rest_api_ref_workbooksviews.htm#publish_workbook

**Comment by irwando** [comment] 2019-07-25 20:21
Duplicate of #315

**Comment by julien10** [comment] 2020-03-31 09:00
Any update on that matter ?

**Comment by shinchris** [comment] 2020-05-04 17:43
This has been added by @scuml in #614.

**Closed by shinchris** 2020-05-04 17:43 UTC
Labels: enhancement, in-progress
